spring:
  profiles: peer1
  application:
    name: tcdp-cloud-eurka-peer
  zipkin:
    base-url: http://localhost:9411
    boot:
      admin:
        client:
          url: http://localhost:8084

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8767/eureka/,http://peer3:8768/eureka/
