spring:
  application:
    name: tcdp-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} #指定实例id


management:
  metrics:
    web:
      server:
        auto-time-requests: false

  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"



